version: "3.7"

x-essentials: &essentials
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

x-postgres: &postgres
  <<:
    - *essentials
  image: postgres:14

services:
  auth-db:
    <<:
      - *postgres
    environment:
      POSTGRES_USER: supertokens
      POSTGRES_PASSWORD: somePassword
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supertokens"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    <<:
      - *essentials
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.2
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://supertokens:somePassword@auth-db:5432/supertokens"
    depends_on:
      - auth-db
    ports:
      - 3567:3567
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
